#!/bin/bash
export XDG_CONFIG_HOME="$HOME"/.config
mkdir -p "$XDG_CONFIG_HOME"

ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
ln -sf "$PWD/nixpkgs" "$XDG_CONFIG_HOME"/nixpkgs
ln -sf "$PWD/zellij" "$XDG_CONFIG_HOME"/zellij
ln -sf "$PWD/bash/dot-bashrc" "$HOME"/.bashrc
ln -sf "$PWD/bash/dot-bash_profile" "$HOME"/.bash_profile

nix-env -iA nixpkgs.myPackages
